/* eslint-disable no-unused-vars */
export enum SystemTable {
  REFRESH_TOKEN = 'RefreshToken',
  USER = 'User',
  CUSTOMER = 'Customer',
  CUSTOMER_DOCUMENT = 'CustomerDocument',
  CUSTOMER_DRIVER_QUALIFIER = 'CustomerDriverQualifier',
  USER_GROUP = 'UserGroup',
  USER_GROUP_TYPE = 'UserGroupType',
  USER_GROUP_SCOPE = 'UserGroupScope',
  ORDER = 'Order',
  ORDER_TYPE = 'OrderType',
  ORDER_ITEM = 'OrderItem',
  PASSWORD_HISTORY = 'PasswordHistory',
  CONTRACT = 'Contract',
  ANALYSIS = 'Analysis',
  ANALYSIS_CUSTOMER = 'AnalysisCustomer',
  ANALYSIS_VEHICLE = 'AnalysisVehicle',
  RESTRICTION = 'Restriction',
  DOCUMENTATION = 'Documentation',
  VEHICLE = 'Vehicle',
  WORKFLOW = 'Workflow',
  WORKFLOW_TASK = 'WorkflowTask',
  NOTIFICATION = 'Notification'
}
