Resources:
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      Path: /eng-roles/
      PermissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/roles-boundary"


# Ajustar os dados do bondary - essa variavel náo existe.